### ISSUE TITLE
v 1.1.0 issue loading config

### ISSUE THREAD

**Issue by robertdmunn** [coldbox-modules/cbox-javaloader#3]
I installed v 1.1.0 via :

`box install cbjavaloader`

and it failed to load my jars with this config in ColdBox.cfc:

```
        javaloader = {
            // The array paths to load
            loadPaths = directoryList( expandPath("./lib/"), true, "array", "*.jar", "name desc" )

        };
```

which works ok in v 1.0.0. The error in ModuleConfig.cfc reported that the path ./ib/myjar.jar was not a directory. Is this a bug or has the API changed?

**Comment by lmajano** [comment]
Hi Robert,

The setting should be

```
// A single path, and array of paths or a single Jar
    loadPaths = [],
```

I believe we had to update this setting in 1.1.0 to meet the documentation
